name: Continuous Delivery
on: [push]
jobs:
  buildDist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Tar
      run: ./gradlew distTar -PAllNatives
    - name: Untar for upload
      run: tar -C artifact -xvf build/distributions/AnarchyEngine.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: compiled
        path: artifact
